### ISSUE TITLE
build options

### ISSUE THREAD

**Issue by fneddy** [mystor/rust-cpp#10]
with version 0.2 it is not any more possible to pass the gcc config struct to the build process (#7). The structure is [defined internally in the crate](https://github.com/mystor/rust-cpp/blob/master/cpp_build/src/lib.rs#L268).

there should be an option to add an includepath to `cpp_build::build`.

**Comment by fneddy** [comment]
should be solved by #11

**Comment by mystor** [comment]
Closed with afbe89b
