### ISSUE TITLE
Updating aho-corasick

### ISSUE THREAD

**Issue by plugwash** [mystor/rust-cpp#108]
Hi

I am currently investigating updating the debian package of the aho-corasick crate to 1.x. we try to keep only one version of each crate in Debian at a time. So this means going through the reverse dependencies and checking if they can be made to build with the new version.

I was able to get the crate to build and tests to pass with a pretty trivial patch (just adding a single ."unwrap()"), but given the paucity of tests I'd appreciate feedback from somone who knows the codebase.

The patch I am considering uploading to Debian can be found at https://salsa.debian.org/rust-team/debcargo-conf/-/blob/93fd56b49a3e6302dda15b04340a2c060c4fa765/src/cpp-macros/debian/patches/update-aho-corasick.diff

**Comment by ogoffart** [comment]
Thanks for the notification.
I released a new release of the crate with the updated version of aho_corasick.

Don't hesitate to make a PR for such things.
