### ISSUE TITLE
It's hard to link to staticly linked library

### ISSUE THREAD

**Issue by uzytkownik** [mystor/rust-cpp#12]
I get the undefined references when I'm accessing symbol from library during linking of print_sizes. As flags are passed before librust_cpp_generated archive they are not used.

**Comment by mystor** [comment]
Thanks for the bug report :).
I've been working on a new way to get the size information in the rust macro which should be more reliable especially when the library is not complete (as the c++ dependency is linked in later). I'll try to push a new version soon.

**Comment by mystor** [comment]
This should be fixed by 6743f6842a05d6729aaf8d36fafa74c872e2f5cb which is in version 0.3.0 (now on crates.io). Please let me know if you still run into problems linking.
