### ISSUE TITLE
function is never used.

### ISSUE THREAD

**Issue by shuaimu** [mystor/rust-cpp#14]
Hello. I am new to rust and want to start by playing with some cxx-rust bindings. 

I followed the example from the document. The compile generated no executable binary with a warning:

```
warning: function is never used: `main`
  --> src/lib.rs:8:1
   |
8  | / fn main() {
9  | |     unsafe {
10 | |         cpp!([] {
11 | |             printf("Hello, World!\n");
12 | |         });
13 | |     }
14 | | }
   | |_^
   |
   = note: #[warn(dead_code)] on by default
```

Is this normal? Any help is appreciated.

**Comment by mystor** [comment]
I think your problem here is that you created a library when you intended to create a binary.
Try either creating your project with `cargo new --bin` instead of `cargo new`, or rename your `lib.rs` file to `main.rs` :-)

**Comment by shuaimu** [comment]
I see. thanks!
