### ISSUE TITLE
Is it possible to use foreign types?

### ISSUE THREAD

**Issue by porky11** [mystor/rust-cpp#16]
Is it, or will it be possible to use types from c++? I didn't find that in the documentation nor in the tests.
I'd like something like that:
```
#[macro_use]
extern crate cpp;

cpp!{{
    #include <glm/glm.hpp> 
}}

fn main() {
    let x = cpp![glm::vec3(1,0,0)];
}

```

**Comment by mystor** [comment]
No, this is not currently possible. 

It might be possible to do something like this (allowing opaque C++ types to exist on the Rust stack - you'd still need cpp! blocks to call methods on the types) once we get something like `impl trait` or if I decide that implicit boxing and virtual call overhead is OK.

**Comment by vadimcn** [comment]
@mystor, btw, why would you need impl Trait for this?

**Comment by mystor** [comment]
I'm not sure if I would. I had one idea for how to implement it which would require it but I haven't had time to think through the options.

**Comment by vadimcn** [comment]
I thought you were talking about creating opaque structs of the same size and alignment as their C++ counterparts.

**Comment by ogoffart** [comment]
This is now possible with cpp_class! from https://github.com/mystor/rust-cpp/pull/28

```rust
#[macro_use]
extern crate cpp;

cpp!{{
    #include <glm/glm.hpp> 
}}

cpp_class!(unsafe struct vec3 as "glm::vec3");

fn main() {
    let x = unsafe { cpp!( [] -> vec3 as "glm::vec3" { return glm::vec3(1,0,0)]; }) };
}
```
