### ISSUE TITLE
"No file with module definition"

### ISSUE THREAD

**Issue by SpaceManiac** [mystor/rust-cpp#17]
Admittedly this is an odd case, but `rust-cpp` can't find a file that `rustc` can:

```rust
pub mod foo {
    pub mod bar;
}
```

No `foo/mod.rs` exists. `rustc` finds `foo/bar.rs` and compiles it, but `rust-cpp` claims "No file with module definition for `mod bar`".

**Comment by mystor** [comment]
This makes sense. cpp-synstructure uses a simple algorithm to try to discover submodules but sometimes doesn't handle directories correctly apparently.

It shouldn't be too hard to make it handle inferring inline modules better, I would think. I won't be able to work on it for a bit though.

**Comment by mystor** [comment]
Fixed by #24
