### ISSUE TITLE
Error parsing when using nested modules

### ISSUE THREAD

**Issue by uzytkownik** [mystor/rust-cpp#23]
I tried to use nested modules

    // lib.rs
    mod foo {
        mod bar;
    }
    // foo/bar.rs
    fn foo() {}

But it causes error:

    warning: -- rust-cpp parse error --
    warning: 
    warning: There was an error parsing the crate for the rust-cpp build script:
    warning: 
    warning: Error while parsing `mod info` statement at lib.rs:2:4
    warning: No file with module definition for `mod bar`
    warning: 
    warning: In order to provide a better error message, the build script will exit
    warning: successfully, such that rustc can provide an error message.

It compiles with `rustc` successfully (well, ignoring linking errors due to missing symbols)

**Comment by mystor** [comment]
I think this was the same as #17. Should be fixed by #24 and on crates.io as version 0.3.2.

**Comment by uzytkownik** [comment]
I can reproduce it with 0.3.2
