### ISSUE TITLE
Compiling on stable

### ISSUE THREAD

**Issue by calebmer** [mystor/rust-cpp#3]
Could a `codegen` extension be created to use this module to compile rust on stable using [`syntex`](https://github.com/serde-rs/syntex)?

**Comment by mystor** [comment]
It could be possible to generate binding code on stable based on this and using syntex. It wouldn't have the type translation features (as in #[repr(C)] types wouldn't have their properties avaliable in C++-land, etc.), but it could be done passing void *-s across the boundary.

It also wouldn't work with macros which generate the cpp! macro, but *meh*.

**Comment by mystor** [comment]
Oh - I never closed this when I moved rust-cpp to stable (it's stable now :+1:)
