### ISSUE TITLE
Invalid escape sequences in #line directives on Windows

### ISSUE THREAD

**Issue by vadimcn** [mystor/rust-cpp#48]
On Windows, cpp_build generates the following #line directive  inside cpp_closures.cpp:
```
#line 245 "C:\Users\vadimcn\.cargo\registry\src\github.com-1ecc6299db9ec823\cpp_build-0.5.1\src\lib.rs"
```
MSVC doesn't seem to mind, but when compiling for  x86_64-pc-windows-gnu target, GCC produces a bunch of warnings and errors like these:
`warning: unknown escape sequence: '\.'`
`error: incomplete universal character name \U`

**Comment by ogoffart** [comment]
Thanks for the bug repport. 
I've been wondering why there was such warnings in the CI output. Now I know.
Should be fixed with https://github.com/mystor/rust-cpp/pull/49

**Comment by m-hilgendorf** [comment]
Just a heads up- this fix isn't published on crates.io. To use the GNU toolchain right now you need to specify the git repo in your manifest.

**Comment by ogoffart** [comment]
By mistake, I pasted the wrong issue in commit 98c1f5b. it did not fix this issue, but the issue #52 

Anyway, this issue was already fixed so it is fine to close it. (Even if there is no updated version on crates.io yet)

**Comment by pfmoore** [comment]
Possibly a dumb question (I'm very new to rust) but I'm hitting this error when trying to build https://github.com/uutils/coreutils - how can I work around it? (Or do I simply need to wait for a new release of rust-cpp?

**Comment by ogoffart** [comment]
Make sure to use the version 0.5.2 of the cpp and cpp_build crate
