### ISSUE TITLE
cpp_class!() reverses lines of doc comments

### ISSUE THREAD

**Issue by mad-s** [mystor/rust-cpp#52]
Pretty much self explanatory. When documenting the following code, the lines of documentation are reversed (i.e. "This is line 2" appears before "This is line 1").

```rust
#[macro_use]
extern crate cpp;

cpp!{{
    class Test {
    };
}}

cpp_class!(
    /// This is line 1
    ///
    /// This is line 2
    pub unsafe struct Test as "Test");
```

**Comment by ogoffart** [comment]
Fixed with commit 98c1f5bf17010a515082854d152f8fc4c4305dd3
(Which unfortunately i pasted a wrong issue number in the commit message)
