### ISSUE TITLE
Structs are private only.

### ISSUE THREAD

**Issue by riomus** [mystor/rust-cpp#6]
Structs in CPP macro are generated as private. Is it possible to make them somehow public to use them in interfaces and other modules? I do not want to rewrite data from structs defined in cpp into public defined in another place.

**Comment by riomus** [comment]
Same problem for enums. I've fixed in my fork in order to use cpp in my project. 

https://github.com/riomus/rust-cpp

If you agree i can create pull request, or you can add those "pub" keywords by yourself. I am not sure how to match "pub" in macro in order to be able to create public and private struct/enums, but that would be best solution.

**Comment by mystor** [comment]
Thanks for the report! I've added a stop-gap fix until we get support for procedural macros (because I don't want to go too deep into macro wizardry) which supports either 100% pub structs or 100% private structs.
