### ISSUE TITLE
cpp! macro with empty capture

### ISSUE THREAD

**Issue by benkay86** [mystor/rust-cpp#66]
Would it be possible to add support for using the cpp! macro without passing anything in from rust?  For symmetry one might add support to the rust! macro to do the same.  For example:

```rust
    cpp!(unsafe [ ] { std::cout << "Hello world!\n"; });
    let the_answer : i32 = cpp!(unsafe [ ] -> i32 as "int32_t" { return 42; });
```

**Comment by ogoffart** [comment]
This is working fine for me.

This is even tested there:

https://github.com/mystor/rust-cpp/blob/9b62bf4d573faea64c9c87c2f408f939b2a13dfe/test/src/lib.rs#L144-L150

What version are you using? What error do you get?

**Comment by benkay86** [comment]
You are quite right, this issue is invalid.  The compiler was generating a misleading error from within the macro for a more complicated test case.  The macro is working exactly as it should.

**Comment by ogoffart** [comment]
What was the misleading error? Perhaps this can be improved?
