### ISSUE TITLE
Linker option?

### ISSUE THREAD

**Issue by kkimdev** [mystor/rust-cpp#7]
Hi, is there a way to specify custom linking options?

**Comment by mystor** [comment]
rust-cpp builds your C++ code with the gcc crate (https://github.com/alexcrichton/gcc-rs), and when calling the build function in rust-cpp, you must pass in a closure, which accepts the config object from gcc. Simply add the flags you want in that callback and you can configure it however you want! Checkout gcc's documentation for details on how the configuration works.
