### ISSUE TITLE
Undefined reference to `__cpp_closure_xxx`

### ISSUE THREAD

**Issue by david-bouyssie** [mystor/rust-cpp#86]
I have tried this crate using the following examples:
https://docs.rs/cpp/0.5.5/cpp/
https://docs.rs/cpp/0.5.5/cpp/macro.cpp.html

However, my linker is failing and prints the following error:
```undefined reference to `__cpp_closure_17383989895670653357'```

What am I doing wrong?

Thanks.

**Comment by ogoffart** [comment]
Looks like the link is failing, What platform are you running on. Are you using linker flag.
the build.rs script should print a line to let cargo know it needs to link against the generated library.

**Comment by david-bouyssie** [comment]
I tried both on Windows x64 and Ubuntu x64.
My rustc version is: 1.47.0 (18bf6b4f0 2020-10-07)

I also tried to git clone the rust-cpp and do a ```cargo test```. I have a similar error.

Note that cxx (https://github.com/dtolnay/cxx) is working, as an alternative solution.

**Comment by ogoffart** [comment]
Looks like a similar problem to https://github.com/mystor/rust-cpp/issues/107
Closing this one as it has less details.
